---
title: "Following the Line of Music"
subtitle: "STAT 231 Blog Project"
author: 
- "Gloria Wu"
- "Justyce Williams"
- "Ben Snyderman"
abstract: "Music is a significant portion of our media consumption - from iconic performances at the Super Bowl and the Grammys to the viral spread of songs on social media platforms. Through this project, we utilize k-means analysis, sentiment analysis, and a network map to explore music."
---

## Introduction

In recent years, music has taken up a significant share of our media consumption - with the rise of digital media services and social media, consumers have little to no barriers to discovering, accessing, and engaging with music (@music_consumption). This observation sparked curiosity in music analysis: we typically think of factors such as genre, lyricism, harmonic frequency, and artist connectivity as being integral to what makes music, music, but what is less clear is which factors really have an impact on the popularity and spread of music. Through this project, we aim to investigate music as a system of patterns, relationships, and compositions, as well as to uncover insights into how music is built, connected, and expressed.    

To analyze these different components of music, we utilize three methods:   
1. [$K$-means analysis](k-means.qmd) to see if there is a "formula," in regards to track features, in determining track popularity.                 
2. [Sentiment analysis](sentiment-analysis.qmd) -        
3. [Network map](network-map.qmd) -         

## Dataset

Data on various songs was taken from the TidyTuesday Spotify dataset by @ttspotify. Included in the dataset was information about the track (such as the name, artist, and genre), and audio features (such as the danceability, tempo, and duration). Release dates of the songs in the dataset range from 1957 to 2020.     

Then, song lyrics were scraped from @genius.

Finally, general information on each track was scraped from @wiki.

## Limitations

Because songs were taken between 1957 to 2020, these results only apply to tracks from that time period. Due to the COVID-19 pandemic, online streaming platforms faced increased demand, leading to a higher quantity of music being produced every year @pandemic. Thus, this sudden change in supply and demand may make the results of this study ungeneralizable beyond 2020.      

Originally, we attempted to scrape data on current popular songs using the `spotifyr` package; however, because Spotify no longer allows for users to get data on tracks, we were unable to do so. Thus, with easier access to current data, we would be more able to analyze current trends and relationships in the music industry.       

- how can study be improved, connect to future work

## Conclusion

Citations were generated using the citation by @cite package. 