---
title: "Sentiment Analysis"
author: "Ben Snyderman"
---

```{r}
#| label: setup
#| include: false

# Improve digit display and NA display for kable tables
options(scipen = 1, knitr.kable.NA = "")

# Load necessary packages
library(tidyverse)
library(dplyr)
library(RColorBrewer)
library(wordcloud)


# Load datasets
load("data/sentiment-data.Rds")
```

### Title

## Subtitle





```{r}


ggplot(data=playlist_nrc_bleeped, aes(x = reorder(word,n), y = n, fill = as.factor(n))) +
geom_col(show.legend = FALSE) +
labs(x = NULL, y = "Frequency") +
facet_wrap(~ sentiment, ncol = 2, scales = "free") +
coord_flip()


```



```{r}

ggplot(data=word_counts_bleeped_sliced, aes(x = reorder(word,n), y = n, fill = as.factor(n))) +
geom_col(show.legend = FALSE) +
labs(x = NULL, y = "Frequency") +
coord_flip()


```







```{r}


set.seed(26)


my_palette2 <- brewer.pal(8, "Dark2")

word_counts_bleeped |>
with(wordcloud(words = word,
freq = n,
max.words = 100,
random.order = TRUE,
scale = c(3, 0.3),
rot.per = 0.15,
colors = my_palette2,
family = "arial"))


```





```{r}


ggplot(afinn_best, aes(x = reorder(track_name, sentiment_score), y = sentiment_score)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "Sentiment Score") +
coord_flip()
```


```{r}
ggplot(afinn_worst, aes(x = reorder(track_name, sentiment_score), y = sentiment_score)) +
  geom_col(show.legend = FALSE) +
  labs(x = NULL, y = "Sentiment Score") +
coord_flip()
```


```{r}

ggplot(data=afinn_rap_pop_good, aes(x = reorder(track_name,sentiment_score), y = sentiment_score, fill = as.factor(sentiment_score))) +
geom_col(show.legend = FALSE) +
labs(x = NULL, y = "Sentiment Score") +
facet_wrap(~ playlist_genre, ncol = 2, scales = "free_y") +
coord_flip()
```


```{r}

ggplot(data=afinn_rap_pop_bad, aes(x = reorder(track_name,sentiment_score), y = sentiment_score, fill = as.factor(sentiment_score))) +
geom_col(show.legend = FALSE) +
labs(x = NULL, y = "Sentiment Score") +
facet_wrap(~ playlist_genre, ncol = 2, scales = "free_y") +
coord_flip()
```




